### ISSUE TITLE
Todo list for v0.2

### ISSUE THREAD

**Issue by Frozenmad** [THUMNLab/AutoGL#35]
@THUMNLab/aglteam 
We are now very close to the new version, and thanks all of the developers for your hardworking and contributions!
We still need the following things done before we finally comes to v0.2:
- [x] tutorial/documents (docstring) on sampling @CoreLeader 
- [x] examples on sampling @CoreLeader 
- [x] tutorial/documents (docstring) on nas @general502570 @wondergo2017 
- [x] examples on nas @general502570 @wondergo2017 
- [x] update dependency and version number @Frozenmad 
- [x] update readme and solver toturial @Frozenmad 

Let's keep working on new versions!
