### ISSUE TITLE
[Internal] checklist for v0.3

### ISSUE THREAD

**Issue by Frozenmad** [THUMNLab/AutoGL#69]
- [x] Heterogeneous trainer and solver adjustment
- [x] Heterogeneous solver test file
- [x] Add the full space of encoder and decoder for test file
- [x] Final performance check
- [x] Test the performance of all examples
- [x] Build the docs

Known issues:
- May not compatible with sampling trainer in v0.2. (solved)
- Cannot support cross module search space dependency. For example, in previous sampling trainer, some hp of trainer may depend on hp of model. While in new version, since spaces of different module are wrapped using dict, we cannot do things like this. (solved, currently the logic is handled by trainer)
